### ISSUE TITLE
Failing to compile Xcode 15.0

### ISSUE THREAD

**Issue by willm132** [damuellen/xlsxwriter.swift#14]
error: cannot assign value of type 'UnsafeMutablePointer<CChar>' (aka 'UnsafeMutablePointer<Int8>') to type 'UnsafePointer<CChar>' (aka 'UnsafePointer<Int8>')

![Screenshot 2023-10-09 at 4 29 33 PM](https://github.com/damuellen/xlsxwriter.swift/assets/47162632/ac14cc10-a5ef-4352-ad8f-b83fc4812b51)

![Screenshot 2023-10-09 at 4 29 46 PM](https://github.com/damuellen/xlsxwriter.swift/assets/47162632/7daa63ee-d4eb-4f5e-a925-f8c0c1365b5b)

**Comment by willm132** [comment]
@damuellen

**Comment by damuellen** [comment]
Hello Will,
unfortunately I can't reproduce the error on my computer.
Can you check if your worksheet.h file looks different from mine.

```

/**
 * @brief Table columns options.
 *
 * Structure to set the options of a table column added with
 * worksheet_add_table(). See @ref ww_tables_columns.
 */
typedef struct lxw_table_column {

    /** Set the header name/caption for the column. If NULL the header defaults
     *  to  Column 1, Column 2, etc. */
    char *header;

    /** Set the formula for the column. */
    char *formula;

    /** Set the string description for the column total.  */
    char *total_string;

    /** Set the function for the column total.  */
    uint8_t total_function;

    /** Set the format for the column header.  */
    lxw_format *header_format;

    /** Set the format for the data rows in the column.  */
    lxw_format *format;

    /** Set the formula value for the column total (not generally required). */
    double total_value;

} lxw_table_column;
```

**Comment by willm132** [comment]
@damuellen I am using the SPM branch since I am using Xcode, so I only have .swift files

**Comment by damuellen** [comment]
Command + Left click on **header**. Xcode will jump to the header file.
```
table_columns[i].header = makeCString(from: header[I])
```

**Comment by damuellen** [comment]
I have tested the SPM branch. Now I also get the errors. Fix coming soon.

**Comment by willm132** [comment]
worksheet.h includes tons of code, the typedef struct lxw_table_column like you asked is included in that file starting on line 1388.

**Comment by willm132** [comment]
@damuellen Awesome, please let me know when you have this fixed, this is preventing me from pushing updates to my software. 

Thanks so much for the quick reply and still support this package. I love it and I use it in everyone of my programs!

**Comment by damuellen** [comment]
Here I show you the difference.

```
/**
 * @brief Table columns options.
 *
 * Structure to set the options of a table column added with
 * worksheet_add_table(). See @ref ww_tables_columns.
 */
typedef struct lxw_table_column {

    /** Set the header name/caption for the column. If NULL the header defaults
     *  to  Column 1, Column 2, etc. */
    const char *header;

    /** Set the formula for the column. */
    const char *formula;

    /** Set the string description for the column total.  */
    const char *total_string;

    /** Set the function for the column total.  */
    uint8_t total_function;

    /** Set the format for the column header.  */
    lxw_format *header_format;

    /** Set the format for the data rows in the column.  */
    lxw_format *format;

    /** Set the formula value for the column total (not generally required). */
    double total_value;

} lxw_table_column;
```

**Comment by willm132** [comment]
Ah yes, that includes the const

**Comment by damuellen** [comment]
I have fixed the error now. Thanks for reporting.

**Comment by willm132** [comment]
The main branch needs to be updated also as it is a requirement for the SPM branch, it is linked in Xcode via the include folder

**Comment by willm132** [comment]
I reset my SPM Cache and updated to latest version but it's still showing const in the include folder under Worksheet lxw_table_column
